config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  get '/signup' => 'users#new'
  post '/signup',  to: 'users#create'

  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :current_user

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :require_user

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      flash[:success] = 'Logged in!'
      redirect_to @user
    else
      flash.now[:danger] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User Successfully created!'
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to "/users/#{@user.id}"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Bec's Ruby and Rails Blog"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:title, "Blogs") %>

<h1>Listing articles</h1>


<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="has-text-centered">
  <p class="is-size-6">Made by me while I work out Ruby syntax</p>
</div>

app/views/layouts/_navbar.html.erb
<% buttonClass = "button is-inverted is-link is-medium" %>

<nav class="navbar navBackground" style="margin-bottom: 2vw">
  <div class="columns">
    <div>
      <% if logged_in? %><p class="is-size-5">You are logged in as <%= current_user.name %></p><% end %>
    </div>
    <div class="columns">

      <h1 class="navbar-brand is-size-1 has-text-link column is-8" style="padding: 1vw">
        Bec's Ruby and Rails Blog
      </h1>

      <div class="column">

        <ul class="navbar-end" style="margin-left: 4vw">
          <li class="linkClass <%= buttonClass %>"><%= link_to 'Home', "/" %></li>
          <% if logged_in? %>
          <div class="dropdown is-hoverable">
            <div class="dropdown-trigger">
              <div class="linkClass <%= buttonClass %>" aria-haspopup="true" aria-controls="dropdown-menu4">
                <span>Users</span>
              </div>
            </div>
            <div class="dropdown-menu" id="dropdown-menu4" role="menu">
              <div class="dropdown-content">
                <li class="linkClass dropdown-item <%= buttonClass %>"><%= link_to "Profile", current_user %></li>
                <li class="linkClass dropdown-item <%= buttonClass %>"><%= link_to "Settings", '#' %></li>
              </div>
            </div>
          </div>

          <li class="linkClass <%= buttonClass %>"><%= link_to 'Logout', logout_path, method: "delete" %></li>
        </ul>
      </div>
      <% else %>
      <li class="linkClass <%= buttonClass %>"><%= link_to 'Login', login_path %></li>
      <li class="linkClass <%= buttonClass %>"><%= link_to 'Signup', signup_path %></li>
    </ul>
  </div>
  <% end %>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
  </head>

  <body>
    <div class="hero">
      <div class="hero-body">
        <%= render "layouts/navbar" %>
        <% flash.each do |message_type, message| %>
          <div class="alert is-size-4 has-text-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
  <div class="error_messages has-text-danger has-text-centered is-size-5">
    <h2>The form contains <%= pluralize(@user.errors.count, "error") %>.</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

app/views/users/_form.html.erb
 <%= form_for(@user, url: signup_path) do |f| %>
  <div class="column is-4 is-offset-4 has-text-centered">
    <div class="field">
      <div class="control">
        <%= f.text_field :name, placeholder: "Name", class: "input is-medium" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.text_field :email, placeholder: "Email", class: "input is-medium" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.password_field :password, placeholder: "Password", class: "input is-medium" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.password_field :password_confirmation, placeholder: "Confirmation", class: "input is-medium" %>
      </div>
    </div>

    <div>
      <%= f.submit "Sign Up", class: 'button is-info is-outlined is-medium' %>
    </div>
  </div>
<% end %>

<%= render 'shared/error_messages' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1 class="is-size-3 has-text-centered has-text-primary">Register New User</h1>

<%= render 'form' %>

<%= link_to 'Back', "/" %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="columns">
  <aside class="column is-6">
    <section class="user_info">
      <h1 class="has-text-centered has-text-link">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<%= @user.email %>

app/views/welcome/index.html.erb
<h1 class="has-text-centered has-text-primary is-size-3">Hello, Rails!</h1>
<p class="has-text-centered has-text-success is-size-5">Click the link to visit my incredibly <em>complicated</em> blog index</p>

<div class="has-text-centered is-size-3 has-text-info"><%= link_to 'My Blog', controller: 'articles'%></div>